version: '1722762889852'
platforms: 
  - key: 'cXE='
    name: '6IW+6K6v'
    enable: true
    site: 'aHR0cHM6Ly92LnFxLmNvbQ=='
    tabs: 
      - key: 'tv'
        name: '电视剧'
      - key: 'movie'
        name: '电影'
      - key: 'cartoon'
        name: '动漫'
    queryer: 'cXE='
    searcher: 'cXE='
    parser: 'Z2VuZXJhbA=='
  - key: 'aXFpeWk='
    name: '54ix5aWH6Im6'
    enable: true
    site: 'aHR0cHM6Ly93d3cuaXFpeWkuY29t'
    tabs: 
      - key: 'tv'
        name: '电视剧'
      - key: 'movie'
        name: '电影'
      - key: 'cartoon'
        name: '动漫'
    queryer: 'aXFpeWk='
    searcher: 'aXFpeWk='
    parser: 'Z2VuZXJhbA=='
  - key: 'eW91a3U='
    name: '5LyY6YW3'
    enable: false
    site: 'aHR0cHM6Ly95b3VrdS5jb20='
    tabs: 
      - key: 'tv'
        name: '电视剧'
      - key: 'movie'
        name: '电影'
      - key: 'cartoon'
        name: '动漫'
    queryer: 'eW91a3U='
    searcher: 'eW91a3U='
    parser: 'Z2VuZXJhbDI='
  - key: 'bWd0dg=='
    name: '6IqS5p6c'
    enable: true
    site: 'aHR0cHM6Ly93d3cubWd0di5jb20='
    tabs: 
      - key: 'tv'
        name: '电视剧'
      - key: 'movie'
        name: '电影'
      - key: 'cartoon'
        name: '动漫'
    queryer: 'bWd0dg=='
    searcher: 'bWd0dg=='
    parser: 'Z2VuZXJhbA=='
  - key: 'YmlsaWJpbGk='
    name: 'QuermQ=='
    enable: true
    site: 'aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29t'
    tabs: 
      - key: 'video'
        name: '推荐'
      - key: 'anime'
        name: '番剧'
    queryer: 'YmlsaWJpbGk='
    searcher: 'YmlsaWJpbGk='
    parser: 'Z2VuZXJhbA=='
